### ISSUE TITLE
不上传到Jetpack？？？

### ISSUE THREAD

**Issue by YumikoAzu** [tianzhijiexian/DBinding#2]

**Comment by tianzhijiexian** [comment]
最近比较忙，所以还没传，如果你觉得项目还行，那么我就会尽快上传。我想问下你的看法呢

**Comment by YumikoAzu** [comment]
~~!! 回复真快  准备 把作者你 写的 指南  多看几遍 理解了 MVVM 和你这个框架 使用   再来用  打算弄毕设、

**Comment by tianzhijiexian** [comment]
哈哈，真是走在了技术的前列呢。这确实是android开发的很新的技术。 不知道你有没有发现，我写的这个和教科书上的东西都变得很不同了。我看时间，如果快今天下午就传。

**Comment by YumikoAzu** [comment]
教科书哪有这种东西学~~~

**Comment by tianzhijiexian** [comment]
已经搞定！
