### ISSUE TITLE
Plugin Error 不能生成对应的ViewModel

### ISSUE THREAD

**Issue by AlphaBoom** [tianzhijiexian/DBinding#4]
Plugin Error: DBinding plugin threw an uncaught StringIndexOutOfBoundsException.
StringIndexOutOfBoundsException: String index out of range:-1

我在Android studio 2.0.0  和 2.1.0 上都会报这个错误

**Comment by bananaCaptain** [comment]
插件没有反应 无法使用

**Comment by bananaCaptain** [comment]
好像安装好插件后,重启电脑就可以用了!!!努力,感谢!

**Comment by AlphaBoom** [comment]
@bananaCaptain 重启电脑之后也还是那个错误，开发环境 mac

**Comment by tianzhijiexian** [comment]
之前也有人上报，我近期看看。

**Comment by tianzhijiexian** [comment]
@AlphaBoom 你直接加我 460412008@qq.com

**Comment by AlphaBoom** [comment]
感谢 @tianzhijiexian 经过一上午排查问题。
问题原因：由于在layout  使用 <import>形式导入的类。该插件是通过type 字段来创建相应model。
解决方案：在type中写完整路径，不使用<import>标签几其他形式。

**Comment by tianzhijiexian** [comment]
我是觉得一个layout里面一种类型的vm肯定只有一个，所以写全名更加简单和好管理，在现在的阶段xml中我强烈建议不要做过多的逻辑和操作。具体参考我的详细文档，文档之外给出的功能，我很可能是不支持的。感谢你的配合，感谢！
