### ISSUE TITLE
如何生成viewmodel

### ISSUE THREAD

**Issue by huahongyang** [tianzhijiexian/DBinding#7]
文档中说在xml中定义好viewmodel 会通过插件（或通过快捷键）出现在相应的包下 请问这个快捷键是什么？为什么我这边没有自动生成viewmodel 下载的插件的2个jar文件要怎么安装？

**Comment by tianzhijiexian** [comment]
这个已经解决了么？

**Comment by huahongyang** [comment]
已经解决了

**Comment by lwmukx1208** [comment]
楼主我还没解决，应该怎么安装那两个插件
